### ISSUE TITLE
There is no need for a test runner for typelevel tests  

### ISSUE THREAD

**Issue by garronej** [danieldietrich/typelevel#16]
Hi @danieldietrich,  

I've been running your readme and your tweets.  
While I am all in for advocating for type level testing, I think it's misleading and pointless to use a test runner framework for test that aren't supposed to be run.  
Tell me if I'm missing something but as I see it there is no point to using Vitest for compile time validation.  
Thoses test will literally never fail.

Anyway, let’s hope compile time testing become mainstream in the next few years.  
Best of luck with `typelevel`.  

Best regards,  

PS: I don't know if you know but while your logo looks rad in dark mode it's not that great with the light theme:  

<img width="934" alt="image" src="https://user-images.githubusercontent.com/6702424/196837809-c45de3d9-8195-455c-83f0-235fdb09270d.png">

It is possible to have a different logo light and dark mode in github: https://dev.to/scopsy/adding-darklight-mode-specific-images-to-your-github-readme-page-3cdj  

NPM doesn't support this syntax yet though so you might want to transform your readme before you publish if you implement this approach.

**Comment by danieldietrich** [comment]
Thank you @garronej for reviewing the repository, that is really helpful!

I've created two separate issues:

• [Dark mode / light mode logo #17](https://github.com/danieldietrich/typelevel/issues/17 )
• [Remove vitest dependency #18](https://github.com/danieldietrich/typelevel/issues/18)

**Comment by danieldietrich** [comment]
Hi @garronej 

* [x] I've removed the vitest dependency
* [x] I've added logos for dark and light mode

The logo now displays correctly on [GitHub](https://github.com/danieldietrich/typelevel/blob/8289f65bad8d8061fb892b5d08d34f82beecd522/README.md) but both logos are shown on [NPM](https://www.npmjs.com/package/typescript-typelevel/v/0.7.5).

I already know that issue from other projects. Are you aware of a solution for fixing it on NPM?

Thx!

**Comment by garronej** [comment]
Hey,  

Thank you for taking in consideration my suggestions!   

I'm glad you agree on the test runner thing.  I'm saying that because I got negative feedback from people that were under the impression that, somehow, the assert function was able to validate at runtime the type of an object. Just like `zod` does.  
We both know it's impossible people that come from the Java are not all aware that type is just scaffolding in TypeScript.   
This is why, I think it's very important that in your documentation and your snippet you make it very explicit. **this is not runtime test** peoples have to understand that the test passes if there is no TS error.     

I got extremely frustrated trying to explain to people the necessity of type level testing, most devs just miss the point, even some that charges 900€+/day for consulting on TypeScript/TDD 😤.  

You got more reach than me on social media, I hope you manage to convince more  people than I did. 

Regarding the logo, I got [this lib](https://github.com/etalab/i18nifty) that has a different logo for the dark and light mode.  
As you can see, I remove the dark logo in the CI before I release on NPM.  https://www.npmjs.com/package/i18nifty  

This is the action that does it:  

https://github.com/etalab/i18nifty/blob/f6ad7bb11514224a416158af7af8e4073c7932c1/.github/workflows/ci.yaml#L102-L104  

You can use only this action or copy paste the workflow as a whole, it's portable.  

It comes from this other project: https://github.com/garronej/ts-ci  

Hope it helps,  

Best regards,

**Comment by danieldietrich** [comment]
Hey Joseph, many thanks for sharing your thoughts and for giving me insight into how you solve build/release challenges! This is really helpful!

I will apply the solution for releasing only one image.

Regarding the "nay sayers": we cannot convince the whole world (wrt type level programming). Visible feedback is often by those who complain. The "yay sayers" who use a solution are silently happy with it. This is my experience.

Typelevel introduces the concept of type-checking. Basically, a function argument type T is "decorated" by with a Check<T> that is implemented by the user of Typelevel. Check returns a CheckResult, which performs a collection of checks. Each check returns (T | CheckError). If one CheckError occurs, the whole Check returns an error. In that case the function call does not accept the user arguments anymore, because an error is expected and the src does not compile anymore.

```ts
// @ts-expect-error
function userApi<A extends any[]>(...someArgs: Check<A>)
```

The ts-expect-error is a "trick" to make the function compile because a CheckError isn't an array. This is what we want: if the actual arguments aren't valid/don't pass the type level checks, the compiler should error and show the check result (a type with an error message and a cause) on mouse hover.

I have implemented such things in a nice real world library that will be released, soon. The community will see how helpful and powerful type level programming is!

Thanks again for your help!

Btw: I will optimize the tsafe type Extends:

```ts
export type Extends<T1, T2> =
    [T1] extends [T2] ? true : false;
```

**Comment by garronej** [comment]
You are welcome,  

> Typelevel introduces the concept of type-checking. Basically, a function argument type T is "decorated" by with a Check 
> that is implemented by the user of Typelevel. Check returns a CheckResult, which performs a collection of checks. Each 
> check returns (T | CheckError). If one CheckError occurs, the whole Check returns an error. In that case the function call 
> does not accept the user arguments anymore, because an error is expected and the src does not compile anymore.  

Sounds very interesting! I'll have to see a concrete example, though.  
Some advice that I can give you, from a marketing standpoint, when you introduce a new concept or feature and you give an example, try to dumb down everything else but the point you are trying to make as much a possible. 
Only introduce one new thing by snippets.  
You want people to focus on the new thing you are trying to show.  
I know it frustrating because we want to show a real life use case that makes sense but people don't go out of their way to try and understand the point if it feels like homework.  

For example, I find this snippet extremely interesting:  
<img width="818" alt="image" src="https://user-images.githubusercontent.com/6702424/197345449-3148ccc5-fde8-480d-b157-01cd288e9f82.png">  

But I think there are too many things introduced at once.  
`Validate`  `ValidationError`   `AssertType` `Is`  
I'm not saying you shouldn't use this it, just that maybe it shouldn't be the first thing users sees. 

Also you should make sure to always have the imports visible so that people understand quickly what are utilities from your lib and what is supposed to come from the ambient context.   

> Btw: I will optimize the tsafe type Extends:  

Cool thanks!

**Comment by danieldietrich** [comment]
@garronej yeah, you are right! The context is missing in the README examples.

Now that I finished the API and the tests, I will give the docs a bit of love.

The examples you see are taken from a repo that will be released as a separate library, soon. The lib uses TypeLevel to do awesome things...
